<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB1zXuJ4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB1zXuJ4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB1zXuJ4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB1zXuJ4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB1zXuJ4\App_KernelDevDebugContainer([
    'container.build_hash' => 'B1zXuJ4',
    'container.build_id' => '1521f01b',
    'container.build_time' => 1679927128,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB1zXuJ4');
