<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmnTJ4E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmnTJ4E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGmnTJ4E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGmnTJ4E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGmnTJ4E\App_KernelDevDebugContainer([
    'container.build_hash' => 'GmnTJ4E',
    'container.build_id' => '3a1539b2',
    'container.build_time' => 1680086047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmnTJ4E');
