<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\adminController::index'], [], [['text', '/admin']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register']], [], [], []],
    'spotbooks_get' => [[], ['_controller' => 'App\\Controller\\SpotbooksController::getSpotBooks'], [], [['text', '/spotbooks']], [], [], []],
    'spotbooks_post' => [[], ['_controller' => 'App\\Controller\\SpotbooksController::addSpotBooks'], [], [['text', '/spotbooks']], [], [], []],
    'app_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
