<?php

namespace ContainerB1zXuJ4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JntLsVvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jntLsVv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jntLsVv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
            'spotbooksRepository' => ['privates', 'App\\Repository\\SpotbooksRepository', 'getSpotbooksRepositoryService', true],
        ], [
            'serializer' => '?',
            'spotbooksRepository' => 'App\\Repository\\SpotbooksRepository',
        ]);
    }
}
